name: CI Front ASV

on:
  push:
  pull_request:

jobs:
  ci:
    name: Install, Lint & Build Expo
    runs-on: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Installation des dépendances
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Build Expo (export statique)
        run: npx expo export --platform web